name: Build and Release

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Get version
        run: |
          chmod +x ./print-version.sh
          version=$(./print-version.sh head=0 build=0)
          echo "version=$version" >> $GITHUB_ENV  # version을 GitHub 환경 변수에 저장
      - name: Push Git tag
        run: |
          git tag "v$version"  # 태그 v$version 생성
          git push origin "v$version"  # 태그 푸시
      - name: Build
        run: |
          ./build.sh $version
      - name: Create GitHub Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
