name: Build and Release

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
      fail-fast: false
    continue-on-error: true
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Get version
        run: |
          chmod +x ./print-version.sh
          echo "VERSION=$(./print-version.sh)" >> $GITHUB_ENV
      - name: Push Git tag
        run: |
          git tag "v$VERSION-$RUNNER_OS"
          git push origin "v$VERSION-$RUNNER_OS"
      - name: Build
        run: |
          ./build.sh $VERSION
      - name: Create GitHub Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          name: "Release v${{ env.VERSION }}-${{ runner.os }}"
          tag_name: "v${{ env.VERSION }}-${{ runner.os }}"
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
